config/routes.rb
FitnessApp::Application.routes.draw do
  resources :users do
    resources :friend_requests, only: [:index]
    resources :goals, only: [:create]
    resources :reports, only: [:new]
    get "reports", on: :member
    get "diary", on: :member
    get "goals", on: :member
    get "friends", on: :member
    resources :weigh_ins, only: [:new]
  end

  resources :daily_entries, only: [:edit, :update, :show] do
    resources :meal_entries, only: [:create, :destroy]
    resources :foods, only: [:show, :index] do
      get "search", on: :collection
    end
    get "search", on: :collection
    post "complete", on: :member
  end

  resources :foods, only: [:new, :show, :create, :index] do
    get "search", on: :collection
  end

  resources :messages, only: [:create, :destroy, :show, :index] do
    put "mark_unread", on: :member
  end
  
  namespace :demo do
    get "new_user"
    get "new_goal"
  end

  resources :meal_entries, only: [:create, :edit, :update]
  resources :diaries, only: [:edit, :update]
  resources :friendships, only: [:create, :destroy]
  resources :friend_requests, only: [:create, :destroy]
  resources :goals, only: [:new, :edit, :destroy, :show]
  resources :feed_items, only: [:create, :destroy]
  resources :weigh_ins, only: [:create, :index]
  resources :reports, only: [:create, :show, :index]
  resource :session, only: [:new, :create, :destroy]

  root to: 'users#home'
end

app/models/message.rb
class Message < ActiveRecord::Base
  attr_accessible :subject, :body, :sender_id, :recipient_id, :is_read

  belongs_to :recipient, class_name: "User", foreign_key: :recipient_id
  belongs_to :sender, class_name: "User", foreign_key: :sender_id
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def index
    @messages = current_user.received_messages.order('created_at DESC').page(params[:page])
    @friends = current_user.friends
    
    if !@messages.empty? && current_user.is_demo
      flash[:demo] = ["Click on a message to open it!"]
    end
  end

  def show
    if current_user.is_demo
      flash[:demo] = ["Thanks for completing the demo. Feel free to explore on your own!"]
    end
    @message = Message.find(params[:id])
    @message.update_attributes(is_read: true)
  end

  def destroy
    @message = Message.find(params[:id])
    @message.destroy
    flash[:notices] = ["Message deleted"]
    redirect_to messages_url
  end

  def create
    recipient_id = params[:message][:recipient_id]
    body = params[:message][:body]
    subject = params[:message][:subject]
    @message = current_user.sent_messages.new(recipient_id: recipient_id, subject: subject, body: body)

    if @message.save
      flash[:notices] = ["Message sent to #{@message.recipient.username}!"]
      redirect_to messages_url
    else
      flash.now[:errors] = @message.errors.full_messages
      render :index
    end
  end

  def mark_unread
    @message = Message.find(params[:id])
    @message.update_attributes(is_read: false)
    redirect_to messages_url
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_message.html.erb
<section class="group message">
  <div class="group sender-info">
    <div class="user-pic">
      <%= image_tag message.sender.profile_picture.url(:thumb) %>
    </div>

  </div>

  <div class="group message-info">
    <div class="float-left">
      <div class="user-link">
        From: <%= link_to "#{message.sender.username}", user_url(message.sender) %>
      </div>

      <div class="subject-line">
        Subject: <%= link_to "#{message.subject}", message_url(message) %>
      </div>
    </div>

    <div class="float-right">
      <form action="<%= message_url(message) %>" method="POST">
        <%= form_auth %>
        <input type="hidden" name="_method" value="delete">
        <input type="submit" value="Delete" class="button">
      </form>

      <% if message.is_read %>
        <form action="<%= mark_unread_message_url(message) %>" method="POST">
          <%= form_auth %>
          <input type="hidden" name="_method" value="put">
          <input type="submit" value="Mark unread" class="button">
        </form>
      <% end %>
    </div>

  </div>
</section>

app/views/messages/_messages.html.erb
<% messages.each do |message| %>
<section class="group message">
  <div class="group sender-info">
    <div class="user-pic">
      <%= image_tag message.sender.profile_picture.url(:thumb) %>
    </div>

  </div>

  <div class="group message-info">
    <div class="float-left">
      <div class="user-link">
        From: <%= link_to "#{message.sender.username}", user_url(message.sender) %>
      </div>

      <div class="subject-line">
        Subject: <%= link_to "#{message.subject}", message_url(message) %>
      </div>
    </div>

    <div class="float-right">
      <form action="<%= message_url(message) %>" method="POST">
        <%= form_auth %>
        <input type="hidden" name="_method" value="delete">
        <input type="submit" value="Delete" class="button">
      </form>
    </div>

  </div>
</section>
<% end %>

app/views/messages/_new_message.html.erb
<form id="new-message" class="group" action="<%= messages_url %>" method="post">
  <%= form_auth %>
  <h1>Send a message</h1>

  <div id="friend-dropdown">
    <label for="friend">Select a friend</label>
    <select name="message[recipient_id]" id="friend">
      <% friends.each do |friend| %>
        <option value="<%= friend.id %>"><%= friend.username %></option>
      <% end %>
    </select>
  </div>

  <div id="subject-line">
    <label for="subject">Subject</label>
    <input type="text" id="subject" name=message[subject]>
  </div>

  <div id="message-body">
    <label for="message">Message</label>
    <textarea id="message" name="message[body]"></textarea>
  </div>

  <div>
    <input type="submit"
      class="button"
      value="Send">
  </div>

</form>

app/views/messages/index.html.erb
<%= render 'shared/title', page_title: "Messages" %>
<%= render 'demo/flashes' %>

<main class="group content">

  <%= render 'shared/errors' %>
  <%= render 'shared/flashes' %>

  <h1>Your inbox</h1>

  <% if @messages.empty? %>
    No messages to display
  <% else %>
    <%= render @messages %>
    <%= paginate @messages %>
  <% end %>

  <% if @friends[0] %>
    <%= render 'new_message', friends: @friends %>
  <% end %>
</main>

app/views/messages/show.html.erb
<%= render 'shared/title', page_title: "Messages" %>

<%= render 'demo/flashes' %>

<main class="group content">
  <article id="show-message" class="group">
    <h1>Subject: <%= @message.subject %></h1>

    <div id="message-text">
      <%= @message.body %>
    </div>

    <div id="message-sender">
      <%= @message.created_at.strftime("Sent on %m/%d/%Y at %I:%M %p") %>
      from <%= link_to "#{@message.sender.username}", user_url(@message.sender) %>
    </div>

    <div id="message-options">
      <form action="<%= message_url(@message) %>" method="POST">
        <%= form_auth %>
        <input type="hidden" name="_method" value="delete">
        <input type="submit" value="Delete" class="button">
      </form>

      <form action="<%= mark_unread_message_url(@message) %>" method="POST">
        <%= form_auth %>
        <input type="hidden" name="_method" value="put">
        <input type="submit" value="Mark unread" class="button">
      </form>
    </div>
  </article>
</main>