config/routes.rb
FitnessApp::Application.routes.draw do
  resources :users do
    resources :friend_requests, only: [:index]
    resources :goals, only: [:create]
    resources :reports, only: [:new]
    get "reports", on: :member
    get "diary", on: :member
    get "goals", on: :member
    get "friends", on: :member
    resources :weigh_ins, only: [:new]
  end

  resources :daily_entries, only: [:edit, :update, :show] do
    resources :meal_entries, only: [:create, :destroy]
    resources :foods, only: [:show, :index] do
      get "search", on: :collection
    end
    get "search", on: :collection
    post "complete", on: :member
  end

  resources :foods, only: [:new, :show, :create, :index] do
    get "search", on: :collection
  end

  resources :messages, only: [:create, :destroy, :show, :index] do
    put "mark_unread", on: :member
  end
  
  namespace :demo do
    get "new_user"
    get "new_goal"
  end

  resources :meal_entries, only: [:create, :edit, :update]
  resources :diaries, only: [:edit, :update]
  resources :friendships, only: [:create, :destroy]
  resources :friend_requests, only: [:create, :destroy]
  resources :goals, only: [:new, :edit, :destroy, :show]
  resources :feed_items, only: [:create, :destroy]
  resources :weigh_ins, only: [:create, :index]
  resources :reports, only: [:create, :show, :index]
  resource :session, only: [:new, :create, :destroy]

  root to: 'users#home'
end

app/views/friends/_approve_or_deny.html.erb
<div class="group friend-buttons">
  <% req_id = current_user.friend_requests.where("friend_id = ?", friend.id).first%>

  <form action="<%= friendships_url(friend: friend) %>" method="POST">
    <%= form_auth %>
    <input type="submit" value="Approve request" class="button">
  </form>

  <form action="<%= friend_request_url(req_id) %>" method="POST">
    <%= form_auth %>
    <input type="hidden" name="_method" value="delete">
    <input type="submit" value="Deny request" class="button">
  </form>
</div>

app/views/friends/_friend.html.erb
<section class="group user-index">

  <%= render 'shared/friend_info', friend: friend %>

  <div class="group friend-buttons">
    <% friendship = current_user.friendships.where("friend_id = ?", friend.id).first %>
    <form action="<%= friendship_url(friendship.id, friend: friend.id) %>" method:"DELETE">
      <%= form_auth %>
      <input type="submit" value="Remove friend" class="button">
    </form>
  </div>

</section>

app/views/friends/_pending.html.erb
<div id="pending-requests">
  <h1>Pending requests</h1>

  <% pending_friends.each do |friend| %>
    <section class="group user-index">
      <%= render 'shared/friend_info', friend: friend %>

      <%= render 'friends/approve_or_deny', friend: friend %>
    </section>
  <% end %>
</div>