config/routes.rb
FitnessApp::Application.routes.draw do
  resources :users do
    resources :friend_requests, only: [:index]
    resources :goals, only: [:create]
    resources :reports, only: [:new]
    get "reports", on: :member
    get "diary", on: :member
    get "goals", on: :member
    get "friends", on: :member
    resources :weigh_ins, only: [:new]
  end

  resources :daily_entries, only: [:edit, :update, :show] do
    resources :meal_entries, only: [:create, :destroy]
    resources :foods, only: [:show, :index] do
      get "search", on: :collection
    end
    get "search", on: :collection
    post "complete", on: :member
  end

  resources :foods, only: [:new, :show, :create, :index] do
    get "search", on: :collection
  end

  resources :messages, only: [:create, :destroy, :show, :index] do
    put "mark_unread", on: :member
  end
  
  namespace :demo do
    get "new_user"
    get "new_goal"
  end

  resources :meal_entries, only: [:create, :edit, :update]
  resources :diaries, only: [:edit, :update]
  resources :friendships, only: [:create, :destroy]
  resources :friend_requests, only: [:create, :destroy]
  resources :goals, only: [:new, :edit, :destroy, :show]
  resources :feed_items, only: [:create, :destroy]
  resources :weigh_ins, only: [:create, :index]
  resources :reports, only: [:create, :show, :index]
  resource :session, only: [:new, :create, :destroy]

  root to: 'users#home'
end

app/models/user.rb
class User < ActiveRecord::Base
  include UsersHelper

  attr_accessible :username,
                  :password,
                  :email,
                  :starting_wt,
                  :current_wt,
                  :goal_wt,
                  :height,
                  :activity_level,
                  :birthday,
                  :about_me,
                  :my_inspiration,
                  :session_token,
                  :gender,
                  :city,
                  :state,
                  :zipcode,
                  :age,
                  :profile_picture,
                  :is_demo
  attr_reader :password

  before_validation :ensure_session_token
  before_save :set_current_weight
  after_create :calculate_user_age
  after_create :create_food_diary

  validates :username, presence: { message: "Please choose a username" }, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }
  validates :password_digest, presence: true
  validates :session_token, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  validates :gender, presence: true, inclusion: { in: %w(M F), message: nil }
  validates :starting_wt, presence: { message: "Please enter your current weight" }
  validates :goal_wt, :height, :activity_level, :birthday, presence: true

  has_one :goal, inverse_of: :user, dependent: :destroy
  has_one :report, dependent: :destroy
  has_many :diaries, dependent: :destroy
  has_many :daily_entries, through: :diaries, source: :daily_entries
  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships, source: :friend
  has_many :friend_requests, dependent: :destroy
  has_many :pending_friends, through: :friend_requests, source: :friend
  has_many :received_messages, class_name: "Message", foreign_key: :recipient_id
  has_many :sent_messages, class_name: "Message", foreign_key: :sender_id
  has_many :feed_items, dependent: :destroy
  has_many :weigh_ins, dependent: :destroy
  has_many :report_items, dependent: :destroy
  has_many :friend_feed_items, through: :friends, source: :feed_items, order: "created_at DESC"
  has_attached_file :profile_picture, styles: { thumb: "75x75>" }, default_url: ActionController::Base.helpers.asset_path('missing.png')

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    storedPassword = BCrypt::Password.new(self.password_digest)
    storedPassword.is_password?(password)
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def self.find_by_credentials(unique_id, password)
    user = User.where("username = ?", unique_id).first
    user ||= User.where("email = ?", unique_id).first

    user.try(:is_password?, password) ? user : nil
  end

  def self.find_by_session_token(session_token)
    User.where("session_token = ?", session_token).includes("goal").first
  end

  private

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def create_food_diary
    self.diaries.create
  end

  def calculate_user_age
    set_user_age(self)
  end

  def set_current_weight
    self.current_wt ||= self.starting_wt
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_logged_in, only: [:index, :show, :update, :destroy, :find, :reports]

  def new
    flash[:demo] = ["Want a tour? Head over to the <a href='/demo/new_user'>demo account</a>!".html_safe]
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.is_demo
      possible_dup = User.where("email = ?", @user.email).first
      if possible_dup && possible_dup.is_demo && possible_dup.persisted?
        possible_dup.destroy
      end

      possible_dup = User.where("username = ?", @user.username).first
      if possible_dup && possible_dup.is_demo && possible_dup.persisted?
        possible_dup.destroy
      end
    end

    if @user.save
      session[:session_token] = @user.session_token
      if @user.is_demo
        redirect_to demo_new_goal_url
      else
        redirect_to new_goal_url
      end
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def index
    if current_user.is_demo
      flash[:demo] ||= ["Click on the 'Add Friend' button to submit a friend request!"]
    end
    @users = User.includes(:friends).includes(:friend_requests).includes(:pending_friends).page(params[:page])
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update_attributes(params[:user])
      flash[:notices] = ["Profile updated!"]
    else
      flash[:errors] = @user.errors.full_messages
    end

    render :edit
  end

  def goals
    render 'goals/show'
  end

  def diary
    if current_user.is_demo
      flash[:demo] ||= ["Try adding a food to your diary. Click on the 'Add Food' button to start."]
    end

    @user = User.includes(:goal).find(params[:id])
    @diary = @user.diaries.first
    @diary ||= @user.diaries.create
    @entry = @diary.daily_entries.where("entry_date = ?", Date.today).first
    @entry ||= @diary.daily_entries.create(entry_date: Date.today)
    @meal_entries = @entry.meal_entries
    @foods = @entry.foods
    render 'diary/show'
  end

  def friends
    @friends = User.includes(:friendships).find(params[:id]).friends
    @user = User.includes(:pending_friends).find(current_user)
    @pending_friends = @user.pending_friends
  end

  def home
    if current_user
      @user = User.includes(:friends).includes(:goal).includes(:daily_entries).find(current_user)
      @daily_entry = @user.daily_entries.where("entry_date = ?", Date.today).first
      @goal = @user.goal
      @calories_remaining = (@daily_entry && @goal) ? @goal.calorie_goal - @daily_entry.calories_consumed : @goal.calorie_goal
      @feed_items = @user.friend_feed_items.page(params[:page])
    else
      flash[:demo] = ["Click here for a guided tour!"]
    end

  end

  def reports
    @report = current_user.report
    @tracked_attr = params[:reportable].pluralize

    if @report.report_items.empty?
    else
      reportable_type = @report.report_items.first.reportable_type
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def set_user_age(user)
    age = Date.today.year - user.birthday.year
    if Date.today.month < user.birthday.month &&
      Date.today.day < user.birthday.day
      age -= 1
    end
    user.update_attributes(age: age)
  end
end

app/views/users/_daily_summary.html.erb
<article class="group">
  <h1>Daily Summary</h1>

  <div id="user-info" class="group">
    <div id="user-picture">
      <%= image_tag current_user.profile_picture.url(:thumb) %>
    </div>

    <div id="pounds-lost">
      <% if current_user.current_wt < current_user.starting_wt %>
        <%= current_user.starting_wt - current_user.current_wt %> pounds lost!
      <% else %>
        0 pounds lost
      <% end %>
    </div>
  </div>

  <div id="food-info" class="group">
    <div id="calorie-box" class="group">
      <div id="calories">
        <%= @calories_remaining %>
      </div>

      <div id="calorie-caption">
        calories remaining
      </div>

      <div id="calorie-breakdown" class="group">
        <%= @daily_entry ? @daily_entry.calories_consumed : 0 %>
        calories consumed
      </div>
    </div>

    <div id="buttons" class="group">
      <form action="<%= diary_user_url(current_user) %>">
        <%= form_auth %>
        <input type="submit" class="button" value="Add food">
      </form>
      <%= render 'shared/goal_button' %>
    </div>
  </div>

</article>

app/views/users/_user.html.erb
<% if user != current_user %>
  <section class="group user-index">
    <%= render 'shared/friend_info', friend: user %>

    <%= render 'shared/friend_buttons', user: user %>
  </section>
<% end %>

app/views/users/edit.html.erb
<%= render 'shared/title', page_title: "Update Info" %>

<main class="group content">

  <form action="<%= user_url(current_user) %>" method="post" enctype="multipart/form-data">
    <h1>Update your profile</h1>

    <%= form_auth %>

    <input type="hidden" name="_method" value="PUT">

    <%= render 'shared/errors' %>
    <%= render 'shared/flashes' %>

    <%= render 'shared/basic_info' %>

    <%= render 'shared/wt_ht_activity' %>

    <%= render 'shared/upload_picture' %>

    <input class="button" type="submit" value="Continue &rarr;">
  </form>

</main>

app/views/users/friends.html.erb
<%= render 'shared/title', page_title: "Friends" %>
<main class="group content">

  <%= render 'shared/errors' %>
  <%= render 'shared/flashes' %>

  <% if @user == current_user && !@pending_friends.empty? %>
    <%= render 'friends/pending', pending_friends: @pending_friends %>
  <% end %>

  <% if @friends.empty? %>
    <div id="no-friends">
      No friends to display!
    </div>
  <% else %>
    <div id="friends">
      <h1>Your Friends</h1>
      <%= render @friends %>
    </div>
  <% end %>

  <div class="link-button">
    <%= link_to "Find friends", users_url %>
  </div>
</main>

app/views/users/home.html.erb
<style>

#homepage-demo div:hover {
	background-color: #E8F797;
}

</style>
<%= render 'shared/title', page_title: "Welcome" %>

<main class="group content">
  <%= render 'shared/errors' %>
  <%= render 'shared/flashes' %>

  <% if current_user %>

    <%= render 'homepage/signed_in_user', friends: @friends, feed_items: @feed_items %>

  <% else %>
  	<div id="homepage-demo">
		<a href="<%= demo_new_user_url %>">
			<%= render 'demo/flashes' %>
		</a>
	</div>

    <%= render 'homepage/not_signed_in' %>

  <% end %>

</main>

app/views/users/index.html.erb
<%= render 'shared/title', page_title: "Members" %>
<%= render 'demo/flashes' %>

<main class="group content">

  <%= render 'shared/errors' %>
  <%= render 'shared/flashes' %>

  <h1>Find Friends!</h1>

  <%= render @users %>
  <%= paginate @users %>

</main>

app/views/users/new.html.erb
<%= render 'shared/title', page_title: "Sign Up" %>

<%= render 'demo/flashes' %>

<main class="group content">

<form action="<%= users_url %>" method="post" enctype="multipart/form-data">
  <h1>Create your free account!</h1>

  <%= form_auth %>
  <input type="hidden" name="user[is_demo]" value="<%= @user.is_demo %>">

  <div class="sign-up-pic">
    <%= image_tag("applecinnamon.png", size: "300x300") %>
  </div>

  <%= render 'shared/errors' %>
  <%= render 'shared/flashes' %>

  <%= render 'shared/basic_info' %>

  <h1>Tell us about yourself</h1>

  <%= render 'shared/wt_ht_activity' %>

  <div>
  Gender
    <input type="radio"
		name="user[gender]"
		value="M" id="male"
		<%= 'checked' if @user.gender == "M" %>>
    <label class="radio" for="male">Male</label>

	<input type="radio"
		name="user[gender]"
		value="F" id="female"
		<%= 'checked' if @user.gender == "F" %>>
    <label class="radio" for="female">Female</label>

    <br>
    <br>
    <%= render 'shared/upload_picture' %>
  </div>

  <div>
    <input class="button" type="submit" value="Continue &rarr;">
  </div>
</form>

</main>

app/views/users/reports.html.erb
<%= render 'shared/title', page_title: @tracked_attr.capitalize %>

<main class="group content">
  <%= render 'shared/flashes' %>
  <%= render 'shared/errors' %>

  <h1>Your Reports</h1>
  <% if @report.report_items.empty? %>
    No data to report!
  <% else %>
    <ul>
      <%= render @report.report_items %>
    </ul>
  <% end %>

  <form action="<%= new_user_report_url(current_user) %>">
    <%= form_auth %>
    <input type="submit" class="button" value="Generate a new report">
  </form>

</main>

app/views/users/show.html.erb
<%= render 'shared/title', page_title: "#{@user.username}" %>

<main class="group content">

  <h1><%= @user.username %>'s Profile</h1>

  <article class="group">

    <div class="group" id="user-profile">
      <div class="group" id="profile-top">
        <div id="user-icon">
          <%= image_tag @user.profile_picture.url(:thumb) %>
        </div>

        <div class="group" id="basic-info">
          <div id="user-asl">
            <ul>
              <li><%= @user.username %></li>
              <li><%= @user.age %></li>
              <li><%= @user.gender %></li>

              <% if @user.city && @user.state %>
                <li><%= @user.city.capitalize %>, <%= @user.state.upcase %></li>
              <% end %>
            </ul>
          </div>

          <% if @user == current_user %>
            <div id="update-profile-button">
              <%= render 'shared/goal_button' %>

              <div class="link-button">
                <%= link_to "Update your profile", edit_user_url(current_user) %>
              </div>
            </div>
          <% end %>
        </div>
      </div>

      <div class="user-details">
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
      </div>

    </div>
  </article>
</main>