config/routes.rb
FitnessApp::Application.routes.draw do
  resources :users do
    resources :friend_requests, only: [:index]
    resources :goals, only: [:create]
    resources :reports, only: [:new]
    get "reports", on: :member
    get "diary", on: :member
    get "goals", on: :member
    get "friends", on: :member
    resources :weigh_ins, only: [:new]
  end

  resources :daily_entries, only: [:edit, :update, :show] do
    resources :meal_entries, only: [:create, :destroy]
    resources :foods, only: [:show, :index] do
      get "search", on: :collection
    end
    get "search", on: :collection
    post "complete", on: :member
  end

  resources :foods, only: [:new, :show, :create, :index] do
    get "search", on: :collection
  end

  resources :messages, only: [:create, :destroy, :show, :index] do
    put "mark_unread", on: :member
  end
  
  namespace :demo do
    get "new_user"
    get "new_goal"
  end

  resources :meal_entries, only: [:create, :edit, :update]
  resources :diaries, only: [:edit, :update]
  resources :friendships, only: [:create, :destroy]
  resources :friend_requests, only: [:create, :destroy]
  resources :goals, only: [:new, :edit, :destroy, :show]
  resources :feed_items, only: [:create, :destroy]
  resources :weigh_ins, only: [:create, :index]
  resources :reports, only: [:create, :show, :index]
  resource :session, only: [:new, :create, :destroy]

  root to: 'users#home'
end

app/views/shared/_basic_info.html.erb
<div>
<label for="username">Username</label>
  <input type="text"
    name="user[username]"
    value="<%= @user.username %>"
    id="username">
</div>

<div>
<label for="email">Email</label>
  <input type="text"
    name="user[email]"
    value="<%= @user.email %>"
    id="email">
</div>

<% unless current_user %>
<div>
<label for="password">Password</label>
  <input type="password"
    name="user[password]"
    id="password">
</div>
<% end %>

<div>
  <label for="birthday">Birthday</label>
    <input type="date"
      name="user[birthday]"
      id="birthday"
      value="<%= @user.birthday %>">
</div>

<div>
  <label for="city">City</label>
    <input type="text"
      name="user[city]"
      id="city"
      value="<%= @user.city %>">
</div>

<div>
  <label for="state">State</label>
    <input type="text"
      name="user[state]"
      id="state"
      value="<%= @user.state %>">
</div>

<div>
  <label for="zipcode">Zip Code</label>
    <input type="text"
      name="user[zipcode]"
      id="zipcode"
      value="<%= @user.zipcode %>">
</div>

app/views/shared/_diary_entry.html.erb
<section id="diary-entry" class="group">
  <% (0..5).each do |num| %>
    <% if @diary.try("meal#{num}".to_sym) %>

    <div class="one-meal">
      <h2><%= @diary.send("meal#{num}".to_sym) %></h2>

      <%= render 'diary/single_meal', meal_entries: @meal_entries, num: num %>

      <% if @user == current_user && date == Date.today %>
      <section class="add-food">
        <div class="link-button">
          <%= link_to "Add food", daily_entry_foods_url(@entry, { meal_num: num }) %>
        </div>
      </section>
      <% end %>
    </div>

    <% else %>
      <% break %>
    <% end %>
  <% end %>
</section>

app/views/shared/_flashes.html.erb
<% if flash[:notices] %>
  <div id="flash-notices">
    <% flash[:notices].each do |notice| %>
      <ul class="notices">
        <li><%= notice %></li>
      </ul>
    <% end %>
  </div>
<% end %>

app/views/shared/_food_search.html.erb
<form id="food-form" class="group">
  <h1>Search the food database</h1>

  <div>
    <label for="food-name">Enter a food</label>
    <input id="food-name" type="text" name="food[name]">
  </div>

  <div>
    <input class="button" type="submit" value="Find foods">
  </div>

  <% if current_user %>
    <div class="link-button">
      <%= link_to "Create a food", new_food_url %>
    </div>
  <% end %>
</form>

<style>
.search-match {
  display: block;
}
</style>

<script>
$('#food-form').on('submit', function (event) {
  event.preventDefault();

  var formData = $(this).serialize();
  console.log("form:" + formData);

  $.ajax({
    url: "foods/search.json",
    type: "GET",
    data: formData,
    success: function (res) {
      var $ul = $('#food-matches');
      $ul.empty();
      if (res.length === 0) {
        $ul.prepend("<li>No matches found!</li>");
      } else {
        res.forEach(function(item) {
          $ul.prepend("<li>" + item.name + "</li>");
        });
      }
    }
  });
});
</script>

app/views/shared/_friend_buttons.html.erb
<div class="group friend-buttons">
  <% if user.friends.include?(current_user) %>

    <div class="remove-friend">

      <% friendship = current_user.friendships.where("friend_id = ?", user.id).first %>
      <form action="<%= friendship_url(friendship.id, friend: user.id) %>" method="POST">
        <%= form_auth %>
        <input type="hidden" name="_method" value="DELETE">
        <input type="submit" value="Remove friend" class="button">
      </form>

    </div>

  <% else %>

    <% if user.pending_friends.include?(current_user) %>

      <div class="requested-friend">
        <% request = user.friend_requests.where("friend_id = ?", current_user.id).first %>

        <form action="<%= friend_request_url(request) %>" method="POST">
          <%= form_auth %>
          <input type="hidden" name="_method" value="DELETE">
          <input type="submit" value="Cancel request" class="button">
        </form>
      </div>

    <% elsif current_user.pending_friends.include?(user) %>

      <div class="pending-friend">

        <form action="<%= friends_user_url(current_user) %>" method="GET">
      <%= form_auth %>
      <input type="submit" value="Respond to request" class="button">
    </form>

      </div>

    <% else %>

      <div class="add-friend">

        <form action="<%= friend_requests_url(friend_id: user.id) %>" method="POST">
          <%= form_auth %>
          <input type="submit" value="Add friend" class="button">
        </form>

      </div>

    <% end%>

  <% end %>
</div>

app/views/shared/_friend_info.html.erb
<div class="group user-info">
	<div class="group float-left">
	  <%= image_tag friend.profile_picture.url(:thumb) %>
  </div>

  <div class="group float-right">
    <ul>
      <li><%= link_to "#{friend.username}", user_url(friend) %></li>
      <li><%= friend.age %></li>
      <li><%= friend.city%>, <%= friend.state %></li>
    </ul>
  </div>
</div>

app/views/shared/_goal_button.html.erb
<% if current_goal %>
  <% button = "Update your goals" %>
  <% url = edit_goal_url(current_goal) %>
<% else %>
  <% button = "Create a goal" %>
  <% url = new_goal_url %>
<% end %>

<form action="<%= url %>">
  <%= form_auth %>
  <input type="submit" class="button" value="<%= button %>">
</form>

app/views/shared/_goal_form.html.erb
<div>
  <label for="workouts">Workouts per week</label>
    <select id="workouts" name="goals[workouts_per_week]">
      <% (1..7).each do |num| %>
        <option value="<%= num %>"
          <%= "selected" if @goal.workouts_per_week == num %>>
          <%= num %>
        </option>
      <% end %>
    </select>
</div>

<div>
  <label for="duration">Minutes per workout</label>
  <input type="text"
    name="goals[minutes_per_workout]"
    id="duration"
    value="<%= @goal.minutes_per_workout %>">
</div>

<div>
  <label for="mygoal">I would like to:</label>
    <select id="mygoal" name="goals[weight_loss_rate]">
      <option <%= "selected" if @goal.weight_loss_rate == -20 %> value="-20">
        Gain two pounds per week
      </option>

      <option <%= "selected" if @goal.weight_loss_rate == -10 %> value="-10">
        Gain one pound per week
      </option>

      <option <%= "selected" if @goal.weight_loss_rate == -5 %> value="-5">
        Gain a half pound per week
      </option>

      <option <%= "selected" if @goal.weight_loss_rate == 0 %> value="0">
        Maintain my current weight
      </option>

      <option <%= "selected" if @goal.weight_loss_rate == 5 %> value="5">
        Lose a half pound per week
      </option>

      <option <%= "selected" if @goal.weight_loss_rate == 10 %> value="10">
        Lose one pound per week
      </option>

      <option <%= "selected" if @goal.weight_loss_rate == 20 %> value="20">
        Lose two pounds per week
      </option>
    </select>
</div>

app/views/shared/_page_top.html.erb
<header>
  <div id="top-strip" class="group">

    <div id="top-strip-content" class="group">
      <div id="logo">
      <%= link_to image_tag("logo.png", size: "128x75"), root_url %>
      </div>

      <section id="user-links" class="group">
        <ul>
        <% if current_user %>
          <li><%= link_to "Hi, #{current_user.username}!", user_url(current_user) %></li>
          <li>
            <% num = "#{current_user.received_messages.where("is_read = ?", false).count}" %>
            <%= link_to "Messages <div id='message-num'>#{num}</div>".html_safe, messages_url %>
            <%=  %>
          </li>
          <li><%= link_to "Help", "#" %></li>
          <li><%= link_to "Sign Out", session_url, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign In", new_session_url %></li>
          <li><%= link_to "Sign Up", new_user_url %></li>
        <% end %>
      </ul>
      </section>
    </div>

  </div>

  <div id="middle-strip" class="group">

  <nav id="middle-strip-content" class="group">
    <section id="main-nav" class="group">
      <ul>
        <% goal_link = current_goal ? goal_url(current_goal) : new_goal_url %>
        <div class="group"><li><%= link_to "Home", root_url %></li></div>
        <% food_link = current_user ? diary_user_url(current_user) : foods_url %>
        <div class="group"><li><%= link_to "Food", food_link %></li></div>
        <% report_link = current_user ? new_user_report_url(current_user) : reports_url %>
        <div class="group"><li><%= link_to "Reports", report_link %></li></div>
        <div class="group"><li><%= link_to "Goals", goal_link %></li></div>
      </ul>
    </section>
  </nav>

</div>

<div id="bottom-strip" class="group">

  <nav class="group bottom-strip-content">
    <ul class="group sub-nav">
      <div><li><%= link_to "Check-in", current_user ? new_user_weigh_in_url(current_user) : weigh_ins_url %></li></div>
      <div><li><%= link_to "Profile", current_user ? user_url(current_user) : "#" %></li></div>
      <div><li><%= link_to "Friends", current_user ? friends_user_url(current_user) : "#" %></li></div>
    </ul>
  </nav>

</div>

<!-- <ul>
  <li>Food Diary</li>
  <li>Database</li>
  <li>My Foods</li>
  <li>My Meals</li>
  <li>Recipes</li>
  <li>Settings</li>
</ul>

<ul>
  <li>Exercise Diary</li>
  <li>Database</li>
  <li>My Exercises</li>
  <li>Settings</li>
</ul> -->

</header>

app/views/shared/_signup_signin.html.erb
<h1>Look at all the cool stuff you can do with my app!</h1>

<ul>
  <li>Keep a food diary</li>
  <li>Find friends</li>
  <li>Set your goals</li>
  <li>Track your progress</li>
</ul>

Sign in or sign up now!

app/views/shared/_title.html.erb
<% content_for :title do %>
  <%= title_helper(page_title) %>
<% end %>

app/views/shared/_upload_picture.html.erb
<div>
  <label for="picture-upload">Upload a profile picture</label>
  <input type="file"
    id="picture-upload"
    name="user[profile_picture]">
</div>

app/views/shared/_user_goal_attr.html.erb
<p>
<label for="current_wt">Current Weight</label>
  <input type="text"
    name="user[current_wt]"
    value="<%= @user.current_wt %>"
    id="current_wt">
</p>

<p>
<label for="goal_wt">Goal Weight</label>
  <input type="text"
    name="user[goal_wt]"
    value="<%= @user.goal_wt %>"
    id="goal_wt">
</p>

<p>
<label>Height: &nbsp
  <select name="user[height]">
    <% (24..99).each do |num| %>
      <option value="<%= num %>"><%= num %></option>
    <% end %>
  </select>
</label>
</p>

<p>Activity Level
  <br>
  <input type="radio" name="user[activity_level]" value="0" id="sedentary">
  <label class="radio" for="sedentary">Sedentary: little to no exercise</label>

  <br>
  <input type="radio" name="user[activity_level]" value="1" id="light_active">
  <label class="radio" for="light_active">Light Activity: light exercise or sports 1-3 days per week</label>

  <br>
  <input type="radio" name="user[activity_level]" value="2" id="moderate">
  <label class="radio" for="moderate">Moderate Activity: moderate exercise or sports 3-5 days per week</label>

  <br>
  <input type="radio" name="user[activity_level]" value="3" id="very_active">
  <label class="radio" for="very_active">Very Active: heavy exercise or sports 6-7 days per week</label>
</p>

app/views/shared/_wt_ht_activity.html.erb
<div>
<label for="current_wt">Current Weight</label>
  <input type="text"
    name="user[current_wt]"
    value="<%= @user.current_wt %>"
    id="current_wt">
</div>

<div>
<label for="goal_wt">Goal Weight</label>
  <input type="text"
    name="user[goal_wt]"
    value="<%= @user.goal_wt %>"
    id="goal_wt">
</div>

<div>
<label>Height: &nbsp
  <select name="user[height]">
    <% (24..99).each do |num| %>
      <option <%= 'selected' if num == @user.height %>
        value="<%= num %>"><%= num %></option>
    <% end %>
  </select>
</label>
</div>

<div>Activity Level
  <br>
  <input type="radio"
    name="user[activity_level]"
    value="0"
    id="sedentary"
    <%= 'checked' if @user.activity_level == 0 %>>
  <label class="radio" for="sedentary">Sedentary: little to no exercise</label>

  <br>
  <input type="radio"
    name="user[activity_level]"
    value="1"
    id="light_active"
    <%= 'checked' if @user.activity_level == 1 %>>
  <label class="radio" for="light_active">Light Activity: light exercise or sports 1-3 days per week</label>

  <br>
  <input type="radio"
    name="user[activity_level]"
    value="2"
    id="moderate"
    <%= 'checked' if @user.activity_level == 2 %>>
  <label class="radio" for="moderate">Moderate Activity: moderate exercise or sports 3-5 days per week</label>

  <br>
  <input type="radio"
    name="user[activity_level]"
    value="3"
    id="very_active"
    <%= 'checked' if @user.activity_level == 3 %>>
  <label class="radio" for="very_active">Very Active: heavy exercise or sports 6-7 days per week</label>
</div>